import type { Metadata } from "next";

import "@/styles/globals.scss";
import { commonMetadata } from "@/common/shared-metadata";
import { FC, PropsWithChildren, useState } from "react";
import { RouteLocale } from "next-roots";
import { yeseva_one, josefin_sans } from "@/styles/font";
import PageWrapper from "@/common/components/PageWrapper/PageWrapper";

export const metadata: Metadata = {
  title: `${commonMetadata.title}`,
  description: "Generated by create next app",
};

type RootLayoutProps = {
  locale: RouteLocale;
};

const RootLayout: FC<PropsWithChildren<RootLayoutProps>> = ({
  locale,
  children,
}) => {
  return (
    <html lang={locale}>
      <body className={`${josefin_sans.variable} ${yeseva_one.variable}`}>
        <PageWrapper>{children}</PageWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
