import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Menu from "@/common/components/Menu/Menu";
import { commonMetadata } from "@/common/shared-metadata";
import { FC } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `${commonMetadata.title}`,
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
